using _2DREPOCODE.Enums;
using System;
using System.Collections.Generic;
using System.Text;

namespace _2DREPOCODE.Models
{
    /// <summary>
    /// Represents a Semibot player character in R.E.P.O.
    /// Handles health, stamina, position, and special abilities like shrinking.
    /// </summary>
    public class Player
    {
        // === Identity ===
        /// <summary>
        /// Unique identifier for this player (useful for multiplayer).
        /// </summary>
        public int PlayerId { get; set; }

        /// <summary>
        /// Player's display name.
        /// </summary>
        public string Name { get; set; }

        // === Position & Movement ===
        /// <summary>
        /// Current X coordinate on the grid.
        /// </summary>
        public int X { get; set; }

        /// <summary>
        /// Current Y coordinate on the grid.
        /// </summary>
        public int Y { get; set; }

        /// <summary>
        /// Direction the player is currently facing.
        /// </summary>
        public Direction Facing { get; set; }

        // === Health System ===
        /// <summary>
        /// Current health points. Player dies when this reaches 0.
        /// </summary>
        public int CurrentHP { get; set; }

        /// <summary>
        /// Maximum health points. Can be increased via upgrades.
        /// </summary>
        public int MaxHP { get; set; }

        /// <summary>
        /// Returns true if player is still alive.
        /// </summary>
        public bool IsAlive => CurrentHP > 0;

        // === Stamina System ===
        /// <summary>
        /// Current stamina. Used for sprinting and special actions.
        /// </summary>
        public float CurrentStamina { get; set; }

        /// <summary>
        /// Maximum stamina. Can be increased via upgrades.
        /// </summary>
        public float MaxStamina { get; set; }

        /// <summary>
        /// Rate at which stamina regenerates per second when not sprinting.
        /// </summary>
        public float StaminaRegenRate { get; set; }

        /// <summary>
        /// Rate at which stamina depletes per second when sprinting.
        /// </summary>
        public float StaminaDrainRate { get; set; }

        /// <summary>
        /// Returns true if player has enough stamina to sprint.
        /// </summary>
        public bool CanSprint => CurrentStamina > 0;

        // === Shrinking Mechanic ===
        /// <summary>
        /// Whether the player is currently in shrunken form.
        /// When shrunk: can hide behind obstacles, access vents, harder for enemies to detect.
        /// </summary>
        public bool IsShrunken { get; set; }

        /// <summary>
        /// The visual size multiplier when shrunken (e.g., 0.5 = half size).
        /// Used for sprite scaling in Unity.
        /// </summary>
        public float ShrinkScale { get; set; }

        // === Equipment & Inventory ===
        /// <summary>
        /// Whether the player is currently holding/tethering an item with the Grabber Tool.
        /// </summary>
        public bool IsHoldingItem { get; set; }

        /// <summary>
        /// Reference to the item currently being tethered (null if none).
        /// </summary>
        public Item? TetheredItem { get; set; }

        /// <summary>
        /// Player's current weapon (can be null if unarmed).
        /// </summary>
        public string? EquippedWeapon { get; set; }

        // === Upgrades & Stats ===
        /// <summary>
        /// Carrying strength - affects how fast player can drag heavy items.
        /// Increased via Service Station upgrades.
        /// </summary>
        public float CarryingStrength { get; set; }

        /// <summary>
        /// Movement speed multiplier (1.0 = normal speed).
        /// </summary>
        public float MovementSpeed { get; set; }

        /// <summary>
        /// Sprint speed multiplier (typically 1.5-2.0x normal speed).
        /// </summary>
        public float SprintSpeedMultiplier { get; set; }

        // === State Flags ===
        /// <summary>
        /// Whether the player is currently sprinting.
        /// </summary>
        public bool IsSprinting { get; set; }

        /// <summary>
        /// Whether the player is currently stunned (cannot move/act).
        /// </summary>
        public bool IsStunned { get; set; }

        /// <summary>
        /// Duration remaining for stun effect (in seconds).
        /// </summary>
        public float StunDuration { get; set; }

        // === Sound System (for Huntsman AI) ===
        /// <summary>
        /// Noise level currently being generated by this player.
        /// 0 = silent, 1 = walking, 2 = sprinting, 3+ = loud actions (breaking items, etc.)
        /// </summary>
        public int NoiseLevel { get; set; }

        // === Constructor ===
        /// <summary>
        /// Creates a new Semibot player with default starting values.
        /// </summary>
        public Player()
        {
            PlayerId = 0;
            Name = "Semibot";

            // Starting position (will be set by MapHandler at spawn point)
            X = 0;
            Y = 0;
            Facing = Direction.South;

            // Default health (can be upgraded)
            MaxHP = 100;
            CurrentHP = MaxHP;

            // Default stamina values
            MaxStamina = 100f;
            CurrentStamina = MaxStamina;
            StaminaRegenRate = 10f; // 10 stamina per second
            StaminaDrainRate = 20f; // 20 stamina per second while sprinting

            // Shrinking mechanic
            IsShrunken = false;
            ShrinkScale = 0.5f; // Half size when shrunk

            // Equipment
            IsHoldingItem = false;
            TetheredItem = null;
            EquippedWeapon = null;

            // Base stats (can be upgraded at Service Station)
            CarryingStrength = 1.0f;
            MovementSpeed = 1.0f;
            SprintSpeedMultiplier = 1.5f;

            // State
            IsSprinting = false;
            IsStunned = false;
            StunDuration = 0f;
            NoiseLevel = 0;
        }

        /// <summary>
        /// Creates a player with custom starting stats (useful for testing/balancing).
        /// </summary>
        public Player(int playerId, string name, int maxHP, float maxStamina)
        {
            PlayerId = playerId;
            Name = name;

            X = 0;
            Y = 0;
            Facing = Direction.South;

            MaxHP = maxHP;
            CurrentHP = MaxHP;

            MaxStamina = maxStamina;
            CurrentStamina = MaxStamina;
            StaminaRegenRate = 10f;
            StaminaDrainRate = 20f;

            IsShrunken = false;
            ShrinkScale = 0.5f;

            IsHoldingItem = false;
            TetheredItem = null;
            EquippedWeapon = null;

            CarryingStrength = 1.0f;
            MovementSpeed = 1.0f;
            SprintSpeedMultiplier = 1.5f;

            IsSprinting = false;
            IsStunned = false;
            StunDuration = 0f;
            NoiseLevel = 0;
        }

        // === Helper Methods ===

        /// <summary>
        /// Takes damage and returns true if player died.
        /// </summary>
        public bool TakeDamage(int damage)
        {
            CurrentHP -= damage;
            if (CurrentHP < 0) CurrentHP = 0;
            return !IsAlive;
        }

        /// <summary>
        /// Heals player by specified amount (cannot exceed MaxHP).
        /// </summary>
        public void Heal(int amount)
        {
            CurrentHP += amount;
            if (CurrentHP > MaxHP) CurrentHP = MaxHP;
        }

        /// <summary>
        /// Drains stamina for sprinting or special actions.
        /// Returns false if not enough stamina available.
        /// </summary>
        public bool DrainStamina(float amount)
        {
            if (CurrentStamina < amount) return false;
            CurrentStamina -= amount;
            return true;
        }

        /// <summary>
        /// Regenerates stamina (called per frame/update).
        /// </summary>
        public void RegenerateStamina(float deltaTime)
        {
            if (!IsSprinting && CurrentStamina < MaxStamina)
            {
                CurrentStamina += StaminaRegenRate * deltaTime;
                if (CurrentStamina > MaxStamina) CurrentStamina = MaxStamina;
            }
        }

        /// <summary>
        /// Toggles the shrinking ability.
        /// </summary>
        public void ToggleShrink()
        {
            IsShrunken = !IsShrunken;
        }

        /// <summary>
        /// Updates noise level based on current action.
        /// 0 = idle/walking slowly, 1 = normal walk, 2 = sprinting, 3+ = loud actions.
        /// </summary>
        public void UpdateNoiseLevel(int level)
        {
            NoiseLevel = level;
        }
    }
}
